In [1]:
import pandas as pd

# Creating the sample data as per the provided schema and values
# SALES Table
sales_data = {
    "Date": ["2023-03-18", "2023-03-18", "2023-01-15", "2023-01-20", "2023-02-05", "2022-12-10"],
    "Order_id": [101, 102, 103, 104, 105, 106],
    "Item_id": [1, 2, 3, 4, 5, 6],
    "Customer_id": [1, 2, 3, 4, 5, 6],
    "Quantity": [2, 1, 3, 1, 2, 1],
    "Revenue": [40.00, 15.00, 75.00, 25.00, 50.00, 15.00]
}
sales_df = pd.DataFrame(sales_data)

# ITEMS Table
items_data = {
    "Item_id": [1, 2, 3, 4, 5, 6],
    "Item_name": ["Widget A", "Widget B", "Widget C", "Widget D", "Widget E", "Widget F"],
    "Price": [20.00, 15.00, 25.00, 25.00, 25.00, 15.00],
    "Department": ["Electronics", "Kitchen", "Electronics", "Outdoors", "Toys", "Outdoors"]
}
items_df = pd.DataFrame(items_data)

# CUSTOMERS Table
customers_data = {
    "Customer_id": [1, 2, 3, 4, 5, 6],
    "First_name": ["John", "Jane", "Sam", "Emily", "Michael", "John"],
    "Last_name": ["Doe", "Smith", "Adams", "Johnson", "Brown", "Doe"],
    "Address": ["123 Maple St", "456 Oak St", "789 Pine St", "321 Elm St", "654 Birch St", "123 Maple St"]
}
customers_df = pd.DataFrame(customers_data)

In [2]:
# 1. Total number of orders completed on 18th March 2023
total_orders_march_18 = sales_df[sales_df['Date'] == "2023-03-18"].shape[0]
total_orders_march_18

2

In [3]:
# 2. Total number of orders completed on 18th March 2023 with first name 'John' and last name 'Doe'
orders_march_18_john_doe = sales_df[(sales_df['Date'] == "2023-03-18") & 
                                    (sales_df['Customer_id'].isin(customers_df[(customers_df['First_name'] == "John") & 
                                                                                  (customers_df['Last_name'] == "Doe")]['Customer_id']))].shape[0]
orders_march_18_john_doe

1

In [4]:
# 3. Total number of customers who purchased in January 2023 and their average spend per customer
january_sales = sales_df[sales_df['Date'].str.startswith("2023-01")]
total_customers_january = january_sales['Customer_id'].nunique()
average_spend_january = january_sales.groupby('Customer_id')['Revenue'].sum().mean()
total_customers_january
average_spend_january

50.0

In [5]:
# 4. Departments that generated less than $600 in 2022
sales_2022 = sales_df[sales_df['Date'].str.startswith("2022")]
department_revenue_2022 = sales_2022.merge(items_df, on='Item_id').groupby('Department')['Revenue'].sum()
departments_under_600 = department_revenue_2022[department_revenue_2022 < 600].index.tolist()
departments_under_600

['Outdoors']

In [6]:
# 5. Most and least revenue generated by an order
most_revenue_order = sales_df['Revenue'].max()
least_revenue_order = sales_df['Revenue'].min()
most_revenue_order
least_revenue_order

15.0

In [7]:
# 6. Orders that were purchased in the most lucrative order
most_lucrative_order = sales_df[sales_df['Revenue'] == most_revenue_order]['Order_id'].values
most_lucrative_order

array([103])